# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Actup < Formula
  desc "Upgrade GitHub Actions versions interactively from your terminal"
  homepage "https://github.com/lynicis/actup"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lynicis/actup/releases/download/v0.1.4/actup_0.1.4_darwin_x86_64.tar.gz"
      sha256 "ef5781881d6eace9c5eda3a5aa45e816d7ecca062452e067aa73bddd5688c0f7"

      define_method(:install) do
        bin.install "actup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lynicis/actup/releases/download/v0.1.4/actup_0.1.4_darwin_arm64.tar.gz"
      sha256 "df038b34c3e4e07d88b9f5bff17607aebea8c70183144a770293871ff312e501"

      define_method(:install) do
        bin.install "actup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lynicis/actup/releases/download/v0.1.4/actup_0.1.4_linux_x86_64.tar.gz"
      sha256 "c2ed5195898a49a1958858e5d77c3c60b80d2a12b83d21391a526f6933934ddc"
      define_method(:install) do
        bin.install "actup"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lynicis/actup/releases/download/v0.1.4/actup_0.1.4_linux_arm64.tar.gz"
      sha256 "01fadf32c750bd7fb332720f078c84e45e98900e2dddac209ad7013c026f7d0b"
      define_method(:install) do
        bin.install "actup"
      end
    end
  end

  test do
    system "#{bin}/actup", "--version"
  end
end
