# This file was generated by GoReleaser. DO NOT EDIT.
cask "actup" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "c16efc59366c574b39e971a930f25c96d455d9467634d9f6391504b67656b1d9"
      url "https://github.com/lynicis/actup/releases/download/v#{version}/actup_#{version}_darwin_x86_64.tar.gz",
        verified: "github.com/lynicis/actup"
    end
    on_arm do
      sha256 "8cf7980c52e7e9457029243dad4dce115fd909780956ae47fed8ebf4169d6ceb"
      url "https://github.com/lynicis/actup/releases/download/v#{version}/actup_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/lynicis/actup"
    end
  end

  on_linux do
    on_intel do
      sha256 "e4ce6b641f8887d29cc7ab6b244613ee2f051edf710120b21ddfba1f68a82e38"
      url "https://github.com/lynicis/actup/releases/download/v#{version}/actup_#{version}_linux_x86_64.tar.gz",
        verified: "github.com/lynicis/actup"
    end
    on_arm do
      sha256 "1248547dbcbb0bb0472f7af8442c63f91dc0981e49a26b6e855b7a327f1e3529"
      url "https://github.com/lynicis/actup/releases/download/v#{version}/actup_#{version}_linux_arm64.tar.gz",
        verified: "github.com/lynicis/actup"
    end
  end

  name "actup"
  desc "Upgrade GitHub Actions versions interactively from your terminal"
  homepage "https://github.com/lynicis/actup"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "actup"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/actup"]
    end
  end

  # No zap stanza required

end
