# This file was generated by GoReleaser. DO NOT EDIT.
cask "actup" do
  version "0.0.0-d1f24c9"

  on_macos do
    on_intel do
      url "https://github.com/lynicis/actup/releases/download/v0.0.0/actup_#{version}_darwin_x86_64.tar.gz",
        verified: "github.com/lynicis/actup"
      sha256 "daea5d2ac5de1bfa9f2bb71cab477b4d3cca166ae3b9bad0e25526cc33335695"
    end
    on_arm do
      url "https://github.com/lynicis/actup/releases/download/v0.0.0/actup_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/lynicis/actup"
      sha256 "af2649e3b1dfc5b3921c8ba67480bd7d60c7749f536ea99c043bbe7ff2626c40"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lynicis/actup/releases/download/v0.0.0/actup_#{version}_linux_x86_64.tar.gz",
        verified: "github.com/lynicis/actup"
      sha256 "14e8d2134465345d3c487a568004c9e12ace2eabf3e7e28c88a4be142f2fbb08"
    end
    on_arm do
      url "https://github.com/lynicis/actup/releases/download/v0.0.0/actup_#{version}_linux_arm64.tar.gz",
        verified: "github.com/lynicis/actup"
      sha256 "169e1a61ee1b3fa02c523f92fa7f49eca25918a322c6baf5f85c495147de1be8"
    end
  end

  name "actup"
  desc "Upgrade GitHub Actions versions interactively from your terminal"
  homepage "https://github.com/lynicis/actup"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "actup"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/actup"]
    end
  end

  # No zap stanza required

end