# This file was generated by GoReleaser. DO NOT EDIT.
cask "actup" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "8079764523a1e14451bf339471b8aa3622625902d86a06f62540eb26cb5a288f"
      url "https://github.com/lynicis/actup/releases/download/v#{version}/actup_#{version}_darwin_x86_64.tar.gz",
        verified: "github.com/lynicis/actup"
    end
    on_arm do
      sha256 "2f3da9beb6716b7ee41eee188ac48b9365b05915e27cda7ecec6566f949b707d"
      url "https://github.com/lynicis/actup/releases/download/v#{version}/actup_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/lynicis/actup"
    end
  end

  on_linux do
    on_intel do
      sha256 "2ee4f239c69c1356736cc79e493c8cfdf175bee3f50cbd5aec1219c1a0e7492e"
      url "https://github.com/lynicis/actup/releases/download/v#{version}/actup_#{version}_linux_x86_64.tar.gz",
        verified: "github.com/lynicis/actup"
    end
    on_arm do
      sha256 "691762fe476fb88d2e557baf2a13459e6baf9c31dd251e00bf26aa5d010a49ba"
      url "https://github.com/lynicis/actup/releases/download/v#{version}/actup_#{version}_linux_arm64.tar.gz",
        verified: "github.com/lynicis/actup"
    end
  end

  name "actup"
  desc "Upgrade GitHub Actions versions interactively from your terminal"
  homepage "https://github.com/lynicis/actup"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "actup"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/actup"]
    end
  end

  # No zap stanza required

end
