# This file was generated by GoReleaser. DO NOT EDIT.
cask "inzibat" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "df2b29a8c113ab0a71e1f7fb3a4a31f50f5806f82933fc7a3a77c78c35588e6f"
      url "https://github.com/lynicis/inzibat/releases/download/v#{version}/inzibat_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "242e21efea81bd52ff8bb395c106a446e74c586701423d51f4fe7ca45febe354"
      url "https://github.com/lynicis/inzibat/releases/download/v#{version}/inzibat_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5db57317cfb6ac9708154f61ffa0301a758f505e270e3f4be9b095b568c665f5"
      url "https://github.com/lynicis/inzibat/releases/download/v#{version}/inzibat_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f2bfa913dbf89f6992af7e5a119199919a8644269eb4058f762c4d7938f7ed2b"
      url "https://github.com/lynicis/inzibat/releases/download/v#{version}/inzibat_Linux_arm64.tar.gz"
    end
  end

  name "inzibat"
  desc "A lightweight HTTP mock server for microservices testing and development"
  homepage "https://github.com/lynicis/inzibat"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "inzibat"

  # No zap stanza required

end
