# This file was generated by GoReleaser. DO NOT EDIT.
cask "inzibat" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "2b83b7d0f0e64d944d430402a9b9d886c38aeaf073fcb297d64f55765303cdaf"
      url "https://github.com/lynicis/inzibat/releases/download/v#{version}/inzibat_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "4ff07ff203c5e8c9de9d703123fc878915c11cdb8c265b92ea52b9d0c03f320f"
      url "https://github.com/lynicis/inzibat/releases/download/v#{version}/inzibat_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "95e68cee78e4b91b0835305c3fc9d43e6bb8dc8ab23a2d96f1bd386cd1167495"
      url "https://github.com/lynicis/inzibat/releases/download/v#{version}/inzibat_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f25d7e16ee88937b59feb904a169bb58430101ecca0f9da57f06211aa6c3575d"
      url "https://github.com/lynicis/inzibat/releases/download/v#{version}/inzibat_Linux_arm64.tar.gz"
    end
  end

  name "inzibat"
  desc "A lightweight HTTP mock server for microservices testing and development"
  homepage "https://github.com/lynicis/inzibat"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "inzibat"

  # No zap stanza required

end
