# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Inzibat < Formula
  desc "A lightweight HTTP mock server for microservices testing and development"
  homepage "https://github.com/lynicis/inzibat"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lynicis/inzibat/releases/download/v0.3.1/inzibat_Darwin_x86_64.tar.gz"
      sha256 "a18f6fe3edecf8739d1241234744272a0c3b85e55e7ed428381f2fc2b85f899a"

      define_method(:install) do
        bin.install "inzibat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lynicis/inzibat/releases/download/v0.3.1/inzibat_Darwin_arm64.tar.gz"
      sha256 "3accb11e5582eaf0f180bfe778b8b4def4db2d88f8f3a5e6ad08705526c15e5a"

      define_method(:install) do
        bin.install "inzibat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lynicis/inzibat/releases/download/v0.3.1/inzibat_Linux_x86_64.tar.gz"
      sha256 "aa66837fab4a205cc9503ada76b9df1f0ef55c3a70a7fbf74197410c090a59ae"
      define_method(:install) do
        bin.install "inzibat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lynicis/inzibat/releases/download/v0.3.1/inzibat_Linux_arm64.tar.gz"
      sha256 "ae97ef84727f4b617ee5c6315cdc673f7619bfc15c1c869c77c0d7366df2bd6c"
      define_method(:install) do
        bin.install "inzibat"
      end
    end
  end

  test do
    system "#{bin}/inzibat", "--help"
  end
end
