# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Inzibat < Formula
  desc "A lightweight HTTP mock server for microservices testing and development"
  homepage "https://github.com/lynicis/inzibat"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lynicis/inzibat/releases/download/v0.3.2/inzibat_Darwin_x86_64.tar.gz"
      sha256 "0bf71b9de7a669ec73eff3728e04e1a7d571113354bae4904a781b5b1e1739b3"

      define_method(:install) do
        bin.install "inzibat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lynicis/inzibat/releases/download/v0.3.2/inzibat_Darwin_arm64.tar.gz"
      sha256 "0b7a69c997b5106dabf606ebfb1eb2c5c066a42edbb908a0bc0c08814a5b01e9"

      define_method(:install) do
        bin.install "inzibat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lynicis/inzibat/releases/download/v0.3.2/inzibat_Linux_x86_64.tar.gz"
      sha256 "94fc32f4dd33158f76394e4c0ef1cfd7b809d3bfefacb20ab30237e971329cdd"
      define_method(:install) do
        bin.install "inzibat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lynicis/inzibat/releases/download/v0.3.2/inzibat_Linux_arm64.tar.gz"
      sha256 "7439bf1a6f3c65c6d8fa78d229ced98047808a534819acd25cb419ea072a9a36"
      define_method(:install) do
        bin.install "inzibat"
      end
    end
  end

  test do
    system "#{bin}/inzibat", "--help"
  end
end
